<?php

use Drupal\user\Entity\User;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the cloud_orchestrator profile.
 */
function cloud_orchestrator_install() {
  // Assign user 1 the "administrator" role.
  $user = User::load(1);
  $user->roles[] = 'administrator';
  $user->save();

  // We install some menu links, so we have to rebuild the router, to ensure the
  // menu links are valid.
  \Drupal::service('router.builder')->rebuildIfNeeded();
}
