; This file was auto-generated by drush make
core = 8.x
api = 2

; Modules
projects[admin_toolbar][version] = "1.27"
projects[authorization][version] = "1.0-beta1"
projects[copyright_footer][version] = "1.3"
projects[ctools][version] = "3.2"
projects[externalauth][version] = "1.1"
projects[ldap][version] = "3.0-beta7"
projects[login_destination][version] = "1.0-alpha2"
projects[module_filter][version] = "3.1"

; Modules
projects[cloud][type] = "module"
projects[cloud][download][type] = "git"
projects[cloud][download][url] = "https://git.drupalcode.org/project/cloud.git"
projects[cloud][download][branch] = "8.x-1.x"
projects[cloud][download][revision] = "2810b722efb2a7ee146584a82c22a9a79d2888c4"

; Libraries
libraries[aws][download][type] = get
libraries[aws][download][url] = "https://github.com/aws/aws-sdk-php/archive/3.108.1.zip"
libraries[aws][destination] = "libraries"

libraries[google][download][type] = get
libraries[google][download][url] = "https://github.com/googleapis/google-api-php-client/archive/v2.2.3.zip"
libraries[google][destination] = "libraries"

; Themes
projects[bootstrap][version] = "3.20"

