piVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay2slack-deployment
  labels:
    app: cowsay2slack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cowsay2slack
  template:
    metadata:
      labels:
        app: cowsay2slack
    spec:
      containers:
      - name: cowsay2slack
        image: docomoinnovations/cloud_orchestrator:cowsay2slack
        env:
        - name: TOKEN
          value: {{TOKEN}}
        restartPolicy: Never
